FROM reactivecircus/android-sdk:latest

MAINTAINER Arunkumar "hi@arunkumar.dev"

LABEL org.opencontainers.image.source="https://github.com/arunkumar9t2/actions-playground"

WORKDIR .

ENV GRADLE_USER_HOME=/root/.gradle

COPY ./cache/.gradle /root/.gradle