FROM reactivecircus/android-sdk-30:latest

LABEL org.opencontainers.image.authors="hi@arunkumar.dev"
LABEL org.opencontainers.image.source="https://github.com/arunkumar9t2/actions-playground"

ENV GRADLE_USER_HOME=/github/home/.gradle

COPY ./cache/.gradle /github/home/.gradle