name: Build workflow

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Set gradle permissions
        run: |
          sudo chmod +x ./gradlew

      - name: Build project
        uses: docker.pkg.github.com/arunkumar9t2/actions-playground/gradledockerimage:latest
        run: |
          ./gradlew assemble