name: CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v1

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1

      - name: Set gradle permissions
        run: |
          chmod +x ./gradlew

      - name: Build project
        run: |
          ./gradlew build
          echo $GRADLE_USER_HOME
          mkdir -p ~/.gradle
          cd ~/.gradle
          ech $(pwd)

      - uses: burrunan/gradle-cache-action@v1
        name: Build
        with:
          job-id: build
          gradle-version: wrapper
          read-only: ${{ github.ref != 'refs/heads/master' }}
          arguments: build