name: Build workflow

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Set gradle permissions
        run: |
          chmod +x ./gradlew
          echo $GRADLE_USER_HOME

      - name: Build project
        run: |
          ./gradlew assemble

      - uses: burrunan/gradle-cache-action@v1
        name: Check with cache
        with:
          job-id: jdk8
          arguments: :check
          gradle-version: wrapper