name: CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Set gradle permissions
        run: |
          chmod +x ./gradlew
          echo $GRADLE_USER_HOME
          sudo apt update
          sudo apt install tree

      - uses: burrunan/gradle-cache-action@v1
        name: Check with cache
        with:
          job-id: jdk8

      - name: Build project
        run: |
          tree ~/.gradle
          ./gradlew build