name: Build workflow

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    container: registry.hub.docker.com/arunkumar9t2/actions-playground:latest
    steps:
      - uses: actions/checkout@v1

      - name: Set gradle permissions
        run: |
          chmod +x ./gradlew
          echo $GRADLE_USER_HOME

      - name: Build project
        run: |
          ./gradlew assemble