name: Gradle docker image workflow

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/gradle_docker.yml'
      - 'docker/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Set gradle permissions
        run: sudo chmod +x ./gradlew

      - name: Prepare gradle cache
        run: |
          cd docker
          export GRADLE_USER_HOME="$(pwd)/cache/.gradle"
          cd ..
          ./gradlew resolveDependencies --no-daemon -g $GRADLE_USER_HOME
          find $GRADLE_USER_HOME -name "*.lock" -type f -delete
          find $GRADLE_USER_HOME -name "gc.properties" -type f -delete

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@2.14
        with:
          name: arunkumar9t2/actions-playground
          username: arunkumar9t2
          password: ${{ secrets.DOCKER_TOKEN }}
          registry: registry.hub.docker.com
          workdir: ${{ github.workspace }}/docker
          dockerfile: Dockerfile