name: Docker image update workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Prepare gradle cache
        run: |
          cd docker
          CURRENT_DIR=$(shell pwd)
          GRADLE_HOME=$(CURRENT_DIR/cache/.gradle)
          echo $GRADLE_HOME
          cd ..
          ./gradlew resolveDependencies -g $(GRADLE_HOME)
