name: Gradle docker image workflow

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/gradle_docker.yml'
      - 'docker/*'
      - '*/gradle-wrapper.properties'
      - '*.gradle'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 1.8

      - name: Set gradle permissions
        run: sudo chmod +x ./gradlew

      - name: Prepare gradle cache
        run: |
          cd docker
          export GRADLE_USER_HOME="$(pwd)/cache/.gradle"
          cd ..
          ./gradlew --version --no-daemon -g $GRADLE_USER_HOME
          ./gradlew resolveDependencies --no-daemon -g $GRADLE_USER_HOME
          find $GRADLE_USER_HOME -name "*.lock" -type f -delete
          find $GRADLE_USER_HOME -name "gc.properties" -type f -delete

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@3.04
        with:
          name: ${{ github.repository }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          workdir: ${{ github.workspace }}/docker
          dockerfile: Dockerfile